# Generated by Django 4.1 on 2022-08-26 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_alter_homework_options_todo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"verbose_name": "todo", "verbose_name_plural": "todo"},
        ),
    ]
